---
title: "learning from data"
author: g.s.
date: July 23, 2018
output:
  revealjs::revealjs_presentation:
    incremental: true
    transition: fade
    highlight: pygments
    center: true
---

## Cosal Inference

* Five Habits of Successful People
	- Adopt these and you will be successful too!

* More frequent system crashes *cause* people to renew their software license.  

* I took this homeopathic medication, and my headache went away!

* *Mayor Giuliani* brought the NYC crime rate down.

## Sins

* Selecting on the dependent variable
	- Think about counterfactuals

* Mistaking correlation for causation
	- No caustion without manipulation

* Not accounting for placebo effects

* Treating temporally proximate as causal

* Thinking $x$ always causes $y$

* $x$ causes $y$ to change a lot

## Average, Above Average, Below Average

* Why (When) do we care about the mean?
	- Sorting is $O(n log n)$
	- When data are symmetrically distributed around it
	- When lots of points are close to it

* How far away is a point from the mean?
	- $(x - \bar{x})$

* How far away from the mean are points on average?
	- Let's say there are $n$ points
	- We just care about the distance, not direction
	- $\frac{\Sigma_1^n (x - \bar{x})^2}{n}$
		- Add 2 units to 2, 12 units to 4. Why? 

## Correlation
	
* $x$ tracks how hot it is outside and $y$ tracks ice-cream sales
	
* When $x$ is large, is $y$ large too?
	- What does that mean?
	
* When $x$ is 1, is $y$ more likely to be 1 than when $x$ is 0?
	
* As $x$ increases, does $y$ increase too?
	- Not precise still
	- On average

* How do you capture that intuition?
 
## Correlation

* For each $x$, $y$, calculate how far it is from its mean

* Then multiply:
	- $\Sigma_1^n (x - \bar{x}) (y - \bar{y})$

* Let's try this out. 
	- 100, 200, 300, 400, 500
	- 1, 2, 3, 4, 5 
	- 1000
		- What do you do with that?

* Normalizing constant
	- $\sqrt{\Sigma_1^n (x - \bar{x})^2 \Sigma_1^n (y - \bar{y})^2}$


## Correlation

- Linear relation
	- Anscombe's quarter
	- More amazing things

## Linear Regression


